### ISSUE TITLE
Official dockerhub image

### ISSUE THREAD

**Issue by vaibhavsood** [jimmidyson/configmap-reload#11]
Hi,

Want to check if there is a docker image for configmap-reload which is a official docker image? I could not find one under dockerhub official images https://hub.docker.com/explore/

If not, want to check if there is any plan to add an official configmap-reload image to dockerhub? https://docs.docker.com/docker-hub/official_repos/#how-do-i-create-a-new-official-repository,

Also want to check if it makes sense to make configmap-reload an official image based on the subjective considerations from the link

**Comment by jimmidyson** [comment]
Not sure this is a good candidate for an official image so closing, but please let me know if you think I'm wrong.
