### ISSUE TITLE
It works for secrets too!

### ISSUE THREAD

**Issue by alice-sawatzky** [jimmidyson/configmap-reload#21]
I think it's worth mentioning in the documentation that it works for secrets too. Both to provide visibility to the feature and to lock it in as something users can rely on.

I assume it uses inotify or something similar, and not the kube API, in which case i would think also a sidecar container generating config files in a shared mount would also trigger it. If this is the case I think it would be useful to document the general versatility of this tool beyond its primary intended use-case of notifying on ConfigMap changes.

**Comment by jimmidyson** [comment]
Great point! This was originally written at a time when only configmaps were automatically rolled out to pods when they changed, not secrets.

**Comment by alice-sawatzky** [comment]
huh that's an interesting bit of history i was not aware of!

**Comment by jimmidyson** [comment]
Added this note to the README! Thanks for the reminder!
