### ISSUE TITLE
configmap-reload binary build fails on s390x

### ISSUE THREAD

**Issue by champashankar** [jimmidyson/configmap-reload#24]
Hi,
I"m trying to build the binary for s390x platform. Getting the below error:
root@platcon3:~/go/src/github.com/img-configmap-reload# ./build.sh
~/go/src/github.com/img-configmap-reload/configmap-reload ~/go/src/github.com/img-configmap-reload

command -v dep >/dev/null 2>&1 || go get github.com/golang/dep/cmd/dep
if [ ! -e /root/go/src/github.com/img-configmap-reload/configmap-reload/_gopath/src/github.com/jimmidyson ]; then mkdir -p /root/go/src/github.com/img-configmap-reload/configmap-reload/_gopath/src/github.com/jimmidyson && ln -s -f /root/go/src/github.com/img-configmap-reload/configmap-reload /root/go/src/github.com/img-configmap-reload/configmap-reload/_gopath/src/github.com/jimmidyson; fi
cd /root/go/src/github.com/img-configmap-reload/configmap-reload/_gopath/src/github.com/jimmidyson/configmap-reload && dep ensure -v
Warning: the following project(s) have [[constraint]] stanzas in Gopkg.toml:

  â  gopkg.in/fsnotify.v1

However, these projects are not direct dependencies of the current project:
they are not imported in any .go files, nor are they in the 'required' list in
Gopkg.toml. Dep only applies [[constraint]] rules to direct dependencies, so
these rules will have no effect.

Either import/require packages from these projects so that they become direct
dependencies, or convert each [[constraint]] to an [[override]] to enforce rules
on these projects, if they happen to be transitive dependencies.

# Gopkg.lock is out of sync with Gopkg.toml and project imports:
gopkg.in/fsnotify/fsnotify.v1: imported or required, but missing from Gopkg.lock's input-imports

Root project is "github.com/jimmidyson/configmap-reload"
 1 transitively valid internal packages
 1 external packages imported from 1 projects
(0)   â select (root)
(1)     ? attempt gopkg.in/fsnotify/fsnotify.v1 with 1 pkgs; at least 1 versions to try
(1)         try gopkg.in/fsnotify/fsnotify.v1@v1.4.7
(1)     â select gopkg.in/fsnotify/fsnotify.v1@v1.4.7 w/1 pkgs
(2)     ? attempt golang.org/x/sys with 1 pkgs; at least 1 versions to try
(2)         try golang.org/x/sys@9c60d1c508f5134d1ca726b4641db998f2523357
(2)     â select golang.org/x/sys@9c60d1c508f5134d1ca726b4641db998f2523357 w/1 pkgs
  â found solution with 2 packages from 2 projects

Solver wall times by segment:
  b-deduce-proj-root: 4.093326944s
     b-source-exists: 3.384806711s
         b-list-pkgs: 224.683871ms
              b-gmal: 126.299402ms
         select-atom:    574.382Âµs
            new-atom:    469.543Âµs
             satisfy:    308.879Âµs
         select-root:     63.467Âµs
               other:     30.708Âµs

  TOTAL: 7.830563907s

(1/2) Wrote gopkg.in/fsnotify/fsnotify.v1@v1.4.7
(2/2) Wrote golang.org/x/sys@9c60d1c508f5134d1ca726b4641db998f2523357
if [ ! -e /root/go/src/github.com/img-configmap-reload/configmap-reload/_gopath/src/github.com/jimmidyson ]; then mkdir -p /root/go/src/github.com/img-configmap-reload/configmap-reload/_gopath/src/github.com/jimmidyson && ln -s -f /root/go/src/github.com/img-configmap-reload/configmap-reload /root/go/src/github.com/img-configmap-reload/configmap-reload/_gopath/src/github.com/jimmidyson; fi
cd /root/go/src/github.com/img-configmap-reload/configmap-reload/_gopath/src/github.com/jimmidyson/configmap-reload && CGO_ENABLED=0 GOARCH=s390x GOOS=linux go build --installsuffix cgo -ldflags="-s -w -extldflags '-static'" -a -o ./out/configmap-reload-linux-s390x configmap-reload.go
# github.com/jimmidyson/configmap-reload/vendor/golang.org/x/sys/unix
vendor/golang.org/x/sys/unix/flock.go:18:42: undefined: Flock_t
vendor/golang.org/x/sys/unix/sockcmsg_linux.go:14:29: undefined: Ucred
vendor/golang.org/x/sys/unix/sockcmsg_linux.go:27:54: undefined: Ucred
vendor/golang.org/x/sys/unix/sockcmsg_unix.go:42:9: undefined: Cmsghdr
Makefile:45: recipe for target 'out/configmap-reload-linux-s390x' failed
make: *** [out/configmap-reload-linux-s390x] Error 2

Could you please help me in resolving the issue.

**Comment by jimmidyson** [comment]
Moved to building in a multi-stage Dockerfile. Please reopen this issue if it is still broken for you.
