### ISSUE TITLE
Dependency on very old sys package

### ISSUE THREAD

**Issue by janotav** [jimmidyson/configmap-reload#29]
Hi,

I have very limited knowledge about GO, so I might be completely off, so please bear with me if that is the case...

It seems that this projects depends on very old version of "golang.org/x/sys". When building the version listed in go.mod is v0.0.0-20150901164945-9c60d1c508f5, which is about 4 years old.

We would like to use the configmap-reload (through prometheus-operator helm chart), but my company has very strict policies when old versions of (four-party) software would be used. Could you please update the dependency to a more recent one?

**Comment by jimmidyson** [comment]
Fixed in #31
