### ISSUE TITLE
Readiness and Liveness checks are missing in the design

### ISSUE THREAD

**Issue by tejaswiniVadlamudi** [jimmidyson/configmap-reload#33]
Hi,

It would be good to add /ready and /healthy end-points to ensure service behaves well in a K8s environment. Do you already have a plan to implement this?

Thanks,
Teja

**Comment by bharathiraja29** [comment]
Hi,

Any current solution for this?

Regards,
Bharathi

**Comment by jimmidyson** [comment]
I don't see a need for probes for this binary, and not even sure what we would check for readiness or liveness probes. I'm going to close this, but if you have a more concrete idea in mind then please feel free to reopen and send in a PR.
