### ISSUE TITLE
New release v0.4.0

### ISSUE THREAD

**Issue by migueleliasweb** [jimmidyson/configmap-reload#45]
Hey @jimmidyson , should we cut a new release? Maybe v0.4.0?

**Comment by jimmidyson** [comment]
Done! Release is [building now](https://app.circleci.com/pipelines/github/jimmidyson/configmap-reload/30/workflows/f9d22828-2b94-49c7-9320-15e799faabb9). Thanks for your contributions!

**Comment by migueleliasweb** [comment]
No problem @jimmidyson ! Thanks for creating the new release!
