### ISSUE TITLE
localhost After a DNS lookup, the wrong ip was found，120.240..95.33。But the real ip of the pod is 100.111.154.159

### ISSUE THREAD

**Issue by huangkaiyan10** [jimmidyson/configmap-reload#47]
2020/07/17 06:19:02 Watching directory: "/etc/prometheus/rules/prometheus-k8s-rulefiles-0"
2020/07/17 06:21:26 config map updated
2020/07/17 06:21:26 performing webhook request (1/1)
2020/07/17 06:21:26 error: Post "http://localhost:9090/-/reload": dial tcp 120.240.95.33:9090: connect: connection refused
2020/07/17 06:21:36 error: Webhook reload retries exhausted

**Comment by andjos** [comment]
Saw the same problem different ip. Found the problem in our dns, we had and localhost.<fqdn> entry. Solved by removing of that entry.

**Comment by jimmidyson** [comment]
Yeah this looks like misconfigured DNS somehow, closing.
