### ISSUE TITLE
Push image to a different registry, in addition to Docker Hub

### ISSUE THREAD

**Issue by onedr0p** [jimmidyson/configmap-reload#58]
**Is your feature request related to a problem? Please describe.**

Dockerhub rate limits

**Describe the solution you'd like**

Push docker image to an additional registry like Quay or GHCR

**Comment by danielhoherd** [comment]
@onedr0p FWIW [astronomer has vendored this configmap-reload binary into a newer busybox container](https://github.com/astronomer/ap-vendor/blob/main/configmap-reloader/Dockerfile#L16-L30) and posted it at https://quay.io/repository/astronomer/ap-configmap-reloader

**Comment by jimmidyson** [comment]
From v0.10.0 this is now available at https://github.com/jimmidyson/configmap-reload/pkgs/container/configmap-reload.

**Comment by onedr0p** [comment]
Thanks @jimmidyson but I think so much time has passed I'm not using this container anymore 🙂
