### ISSUE TITLE
ca-certificates not installed, cannot hit https reload endpoints

### ISSUE THREAD

**Issue by Saqibm128** [jimmidyson/configmap-reload#9]
Cannot reload if we hit an https: reload endpoint, since ca-certificates is not installed.
(how would one install on scratch container, though?)

**Comment by jimmidyson** [comment]
Good point! We can switch to use [`gcr.io/distroless/base`](https://github.com/GoogleCloudPlatform/distroless/blob/master/base/README.md) instead perhaps?

**Comment by dannyk81** [comment]
Possibly fixed in https://github.com/jimmidyson/configmap-reload/pull/15 ?

**Comment by jimmidyson** [comment]
Fixed in #15
