### ISSUE TITLE
arm images broken for v0.10 and v0.11

### ISSUE THREAD

**Issue by dschaaff** [jimmidyson/configmap-reload#90]
The error `exec /configmap-reload: exec format error` is given when attempting to run either the 0.10 or 0.11 images on arm nodes. 0.9 and older work correctly.

**Comment by jimmidyson** [comment]
Oops sorry! Fixed in #91. Will release ASAP

**Comment by jimmidyson** [comment]
This is fixed in v0.11.1 - thanks for reporting!

**Comment by dschaaff** [comment]
Thanks!
