### ISSUE TITLE
nonroot user mismatch

### ISSUE THREAD

**Issue by miguelhar** [jimmidyson/configmap-reload#94]
Hello, given that upstream image [NONROOT](https://github.com/GoogleContainerTools/distroless/blob/main/base/base.bzl#L8C7-L8C16) user is different than `USER`

```
NONROOT = 65532
```
vs
```
USER 65534
```
Dont we need 

```
RUN chown -R 65534:65534 /home/nonroot
```
in order to avoid:
```
OCI runtime create failed: container_linux.go:346: starting container process caused "chdir to cwd (\"/home/nonroot\") set in config.json failed: permission denied"
```
I have been able to mitigate the issue in 2 ways:

1. Update the container scc to run as user: `65532`
2. Set container `workingDir: "/"`

**Comment by jimmidyson** [comment]
Oops! Thanks for reporting! Let's just change the `USER` in the Dockerfile to 65532 - would you like to send in a PR to do that? 🙏
